import 'package:flutter/material.dart';

class TelaTeste extends StatelessWidget {
  const TelaTeste({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: [
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("testea"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("tesate"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teaste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("tesate"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("tesate"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("tesate"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
          Text("teste"),
        ],
      ),
    );
  }
}